name: KingdomsOfArden-ToolHandler
version: 2.1.3-dev
description: Handles durability based enchantments such as prot and sharpness, as well as lore based weapon bonuses and modifications
author: Andrew2060
website: http://www.kingdomsofarden.net/
main: net.kingdomsofarden.andrew2060.toolhandler.ToolHandlerPlugin
depend: [Heroes, Vault]
commands:
    toolhandler: 
        description: Reloads configs and reloads all mods from disk
        usage: /<command>
        permission: toolhandler.root
    modtool:
        description: Applies the selected mod to the tool
        usage: /<command> modname
        permission: toolhandler.mod
    refreshtoollore:
        description: Refreshes the lore on a tool in hand to bring it up to date
        usage: /<command>
        permission: toolhandler.refresh